### ISSUE TITLE
Cant use single quote

### ISSUE THREAD

**Issue by milewski** [danielkalen/foreach-cli#3]
I dont understand coffescript to do a PR myself.. but could you accept single quotes on the options as well as double? currently this doesnt work:

```json
"scripts": {
  "build:config": "foreach --glob 'webpack/**/*.ts' --execute 'tsc #{path}' --no-c",
},
```

because of the 'single' quote... only if i change to `\"webpack/**/*.ts\"` it works

**Comment by danielkalen** [comment]
Hmm... what happens if you copy/paste that command directly in the cli? The thing is that in bash single quotes [prevent string interpolation](http://www.gnu.org/software/bash/manual/html_node/Single-Quotes.html) as opposed to [double quotes](http://www.gnu.org/software/bash/manual/html_node/Double-Quotes.html) but in the case of asterisk wildcards in either type they shouldn't be [expanded](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html#Shell-Parameter-Expansion) and should therefore be passed to the program as is... What you demonstrated doesn't really add up for me because it shouldn't be behaving that way which makes me think it's something related to the way NPM handles & parses the commands - which also doesn't make sense for me as I use single quotes for all my `foreach` commands in npm scripts too.

Try running it directly in the shell and let me know if that behavior carries on there

**Comment by milewski** [comment]
okay i have narrowed down this issue to -> `Windows/cmd` looks like npm uses CMD instead of BASH on windows (might be configurable) ...

so running it directly (using single quotes) `on bash it works`, `on cmd doesn't`, `on power-shell works`

**Comment by danielkalen** [comment]
So it seems like it is an issue related directly with the shell the command is being run with which we have no control over... Feel free to reopen this issue if needed.
