### ISSUE TITLE
Command fails to execute: 'FORCE_COLOR' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by jessehouwing** [danielkalen/foreach-cli#6]
Node: v10.8.0
npm: 6.3.0
Windows: 10 (1803)

When running this command: 
```
npm install && foreach -g "x/!(*.json)" -x "pushd #{path} && npm install && popd" -C -c
```

I get:

```
 × Executing command: x/y
 × Executing command: x/z

Error x/y
'FORCE_COLOR' is not recognized as an internal or external command,
operable program or batch file.

Error x/z
'FORCE_COLOR' is not recognized as an internal or external command,
operable program or batch file.
```

I can suppress this by adding:

```
npm install && foreach -g "x/!(*.json)" -x "pushd #{path} && npm install && popd" -C --no-c
```

**Comment by garretwilson** [comment]
This is happening to me as well on Windows 10.

Node: v10.10.0
npm: 6.4.1

**Comment by danielkalen** [comment]
I believe this is a windows-specific issue related to windows' syntax for declaring env variables for individual commands.

The issue lies in here: https://github.com/danielkalen/foreach-cli/blob/38ae0aeb19927969b503d1f2f331fdd6ca5cb425/lib/foreach.coffee#L35

The program adds an env var declaration prior to each command that is run in order to ensure that rich color support.

To be honest I don't know my way around windows shell nor how env variables are declared but I am assuming that it's different than UNIX and that this is why you are receiving that error. If anyone can provide me with some input on how to declare env variables on windows I can add special handling for windows use cases.

**Comment by jessehouwing** [comment]
I don't think this is possible on windows. You can call `cmd /c set FORE_COLOR=x & command` to launch a console, set the variable locally in that console. And then launch the command.

**Comment by danielkalen** [comment]
I see. So I guess removing this `FORCE_COLOR` var declaration under windows env would be the only reasonable route here. I will take care of this in the next few days

**Comment by danielkalen** [comment]
https://github.com/danielkalen/foreach-cli/commit/93661e31f5bda92580e9b84fa418d28c847a9d6c

**Comment by garretwilson** [comment]
Thanks for fixing this! I upgrade to v1.8.1, and that seems to have solved the problem.

Have you considered tagging releases so they will show up at https://github.com/danielkalen/foreach-cli/releases ? I had to remember how to get to https://www.npmjs.com/package/foreach-cli in order to figure out the new version number. That might be helpful. Cheers.
